services:
  db:
    container_name: "db_task_manager"
    image: "postgres:17"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    ports:
      - 5432:5432
    networks:
      - db
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5000:80
    networks:
      - db
networks:
  db:
    driver: bridge