services:
  db:
    container_name: "db_task_manager"
    image: "postgres:17"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    ports:
      - 5432:5432
    networks:
      - db_net
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5000:80
    networks:
      - db_net

  app:
    build: ./
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 80:8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=db     
    networks:
      - db_net
    depends_on:
      - db
      
networks:
  db_net:
    driver: bridge