"""add author column

Revision ID: e4a703181c9e
Revises: 30503bdb2396
Create Date: 2025-07-02 16:11:56.705288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a703181c9e'
down_revision: Union[str, Sequence[str], None] = '30503bdb2396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('author_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_task_user', 'task', 'user', ['author_id'], ['id'])
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_constraint('fk_task_user', 'task', type_='foreignkey')
    op.drop_column('task', 'author_id')
    # ### end Alembic commands ###
